Update gray-matter.d.ts
Typescript was returning a set of errors for gray-matter types:

```
node_modules/gray-matter/gray-matter.d.ts(34,56): error TS7006: Parameter 'object' implicitly has an 'any' type.
```
This PR adds a variable name to the types which makes TS happy.